import type { Metadata } from 'next';
import Navbar from './components/Navbar';
import './styles/globals.css';

export const metadata: Metadata = {
  title: 'Next js playground',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-dvh min-w-full flex flex-col gap-2">
        <Navbar />
        <div className="p-4"></div>
        {children}
      </body>
    </html>
  );
}
